@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}


### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "andrade@email.com",
  "password": "123456"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}


### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Andrade",
  "email": "andrade@email.com",
  "password": "123456"
}

### Update User
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Andrade",
  "email": "andrade@email.com"
}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "123456",
  "newPassword": "1234567"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Delete one user
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}


